//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfSysDCAA.Properties.Application_data {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class user : global::System.Configuration.ApplicationSettingsBase {
        
        private static user defaultInstance = ((user)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new user())));
        
        public static user Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MD5SystemChecksum {
            get {
                return ((string)(this["MD5SystemChecksum"]));
            }
            set {
                this["MD5SystemChecksum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string field_db_host {
            get {
                return ((string)(this["field_db_host"]));
            }
            set {
                this["field_db_host"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string field_db_name {
            get {
                return ((string)(this["field_db_name"]));
            }
            set {
                this["field_db_name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string field_db_user {
            get {
                return ((string)(this["field_db_user"]));
            }
            set {
                this["field_db_user"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string field_db_password {
            get {
                return ((string)(this["field_db_password"]));
            }
            set {
                this["field_db_password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\Documents\\InfSysDCAA\\Reports")]
        public string path_doc_reports {
            get {
                return ((string)(this["path_doc_reports"]));
            }
            set {
                this["path_doc_reports"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\Documents\\InfSysDCAA\\Raw Files")]
        public string path_doc_raw_files {
            get {
                return ((string)(this["path_doc_raw_files"]));
            }
            set {
                this["path_doc_raw_files"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\Documents\\InfSysDCAA\\Config")]
        public string path_doc_config {
            get {
                return ((string)(this["path_doc_config"]));
            }
            set {
                this["path_doc_config"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string field_ftp_host {
            get {
                return ((string)(this["field_ftp_host"]));
            }
            set {
                this["field_ftp_host"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string field_ftp_login {
            get {
                return ((string)(this["field_ftp_login"]));
            }
            set {
                this["field_ftp_login"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string field_ftp_password {
            get {
                return ((string)(this["field_ftp_password"]));
            }
            set {
                this["field_ftp_password"] = value;
            }
        }
    }
}
