-- MySQL Script generated by MySQL Workbench
-- 04/09/16 00:48:10
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema isvsk_v2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `isvsk_v2` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `isvsk_v2` ;

-- -----------------------------------------------------
-- Table `isvsk_v2`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `isvsk_v2`.`employees` (
  `id` INT(5) UNSIGNED NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `secondname` VARCHAR(45) NOT NULL,
  `position` VARCHAR(255) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `isvsk_v2`.`plus5v`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `isvsk_v2`.`plus5v` (
  `id` INT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `minimum` INT(3) NOT NULL,
  `medium` INT(3) NOT NULL,
  `maximum` INT(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `isvsk_v2`.`minus12v`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `isvsk_v2`.`minus12v` (
  `id` INT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `minimum` INT(3) NOT NULL,
  `medium` INT(3) NOT NULL,
  `maximum` INT(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `isvsk_v2`.`plus12vPause`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `isvsk_v2`.`plus12vPause` (
  `id` INT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `minimum` INT(3) NOT NULL,
  `medium` INT(3) NOT NULL,
  `maximum` INT(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `isvsk_v2`.`plus12v25time`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `isvsk_v2`.`plus12v25time` (
  `id` INT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `minimum` INT(3) NOT NULL,
  `medium` INT(3) NOT NULL,
  `maximum` INT(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `isvsk_v2`.`plus12v50time`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `isvsk_v2`.`plus12v50time` (
  `id` INT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `minimum` INT(3) NOT NULL,
  `medium` INT(3) NOT NULL,
  `maximum` INT(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `isvsk_v2`.`plus12v100time`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `isvsk_v2`.`plus12v100time` (
  `id` INT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `minimum` INT(3) NOT NULL,
  `medium` INT(3) NOT NULL,
  `maximum` INT(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `isvsk_v2`.`power_requirements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `isvsk_v2`.`power_requirements` (
  `id` INT(5) NOT NULL,
  `plus5v_id` INT(5) UNSIGNED NOT NULL,
  `minus12v_id` INT(5) UNSIGNED NOT NULL,
  `plus12vPause_id` INT(5) UNSIGNED NOT NULL,
  `plus12v25time_id` INT(5) UNSIGNED NOT NULL,
  `plus12v50time_id` INT(5) UNSIGNED NOT NULL,
  `plus12v100time_id` INT(5) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_power_requirements_plus5v_idx` (`plus5v_id` ASC),
  INDEX `fk_power_requirements_minus12v1_idx` (`minus12v_id` ASC),
  INDEX `fk_power_requirements_plus12vPause1_idx` (`plus12vPause_id` ASC),
  INDEX `fk_power_requirements_plus12v25time1_idx` (`plus12v25time_id` ASC),
  INDEX `fk_power_requirements_plus12v50time1_idx` (`plus12v50time_id` ASC),
  INDEX `fk_power_requirements_plus12v100time1_idx` (`plus12v100time_id` ASC),
  CONSTRAINT `fk_power_requirements_plus5v`
    FOREIGN KEY (`plus5v_id`)
    REFERENCES `isvsk_v2`.`plus5v` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_power_requirements_minus12v1`
    FOREIGN KEY (`minus12v_id`)
    REFERENCES `isvsk_v2`.`minus12v` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_power_requirements_plus12vPause1`
    FOREIGN KEY (`plus12vPause_id`)
    REFERENCES `isvsk_v2`.`plus12vPause` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_power_requirements_plus12v25time1`
    FOREIGN KEY (`plus12v25time_id`)
    REFERENCES `isvsk_v2`.`plus12v25time` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_power_requirements_plus12v50time1`
    FOREIGN KEY (`plus12v50time_id`)
    REFERENCES `isvsk_v2`.`plus12v50time` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_power_requirements_plus12v100time1`
    FOREIGN KEY (`plus12v100time_id`)
    REFERENCES `isvsk_v2`.`plus12v100time` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `isvsk_v2`.`temperature`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `isvsk_v2`.`temperature` (
  `id` INT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `minimum` INT(3) NOT NULL,
  `medium` INT(3) NOT NULL,
  `maximum` INT(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `isvsk_v2`.`out_diff_volt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `isvsk_v2`.`out_diff_volt` (
  `id` INT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `minimum` INT(3) NOT NULL,
  `medium` INT(3) NOT NULL,
  `maximum` INT(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `isvsk_v2`.`rise_and_fall_time_signal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `isvsk_v2`.`rise_and_fall_time_signal` (
  `id` INT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `minimum` INT(3) NOT NULL,
  `medium` INT(3) NOT NULL,
  `maximum` INT(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `isvsk_v2`.`transmitter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `isvsk_v2`.`transmitter` (
  `id` INT(5) NOT NULL,
  `out_diff_volt_id` INT(5) UNSIGNED NOT NULL,
  `rise_and_fall_time_signal_id` INT(5) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_transmitter_out_diff_volt1_idx` (`out_diff_volt_id` ASC),
  INDEX `fk_transmitter_rise_and_fall_time_signal1_idx` (`rise_and_fall_time_signal_id` ASC),
  CONSTRAINT `fk_transmitter_out_diff_volt1`
    FOREIGN KEY (`out_diff_volt_id`)
    REFERENCES `isvsk_v2`.`out_diff_volt` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_transmitter_rise_and_fall_time_signal1`
    FOREIGN KEY (`rise_and_fall_time_signal_id`)
    REFERENCES `isvsk_v2`.`rise_and_fall_time_signal` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `isvsk_v2`.`reciver_in_diff_v`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `isvsk_v2`.`reciver_in_diff_v` (
  `id` INT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `minimum` INT(3) NOT NULL,
  `medium` INT(3) NOT NULL,
  `maximum` INT(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `isvsk_v2`.`device_manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `isvsk_v2`.`device_manager` (
  `id` INT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `inventnumber` VARCHAR(15) NOT NULL,
  `serialnumber` VARCHAR(40) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `manufacturer` VARCHAR(150) NOT NULL,
  `power_requirements_id` INT(5) NOT NULL,
  `temperature_id` INT(5) UNSIGNED NOT NULL,
  `transmitter_id` INT(5) NOT NULL,
  `reciver_in_diff_v_id` INT(5) UNSIGNED NOT NULL,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  PRIMARY KEY (`inventnumber`, `serialnumber`),
  UNIQUE INDEX `inventnumber_UNIQUE` (`inventnumber` ASC),
  UNIQUE INDEX `serialnumber_UNIQUE` (`serialnumber` ASC),
  INDEX `fk_device_manager_power_requirements1_idx` (`power_requirements_id` ASC),
  INDEX `fk_device_manager_temperature1_idx` (`temperature_id` ASC),
  INDEX `fk_device_manager_transmitter1_idx` (`transmitter_id` ASC),
  INDEX `fk_device_manager_reciver_in_diff_v1_idx` (`reciver_in_diff_v_id` ASC),
  CONSTRAINT `fk_device_manager_power_requirements1`
    FOREIGN KEY (`power_requirements_id`)
    REFERENCES `isvsk_v2`.`power_requirements` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_device_manager_temperature1`
    FOREIGN KEY (`temperature_id`)
    REFERENCES `isvsk_v2`.`temperature` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_device_manager_transmitter1`
    FOREIGN KEY (`transmitter_id`)
    REFERENCES `isvsk_v2`.`transmitter` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_device_manager_reciver_in_diff_v1`
    FOREIGN KEY (`reciver_in_diff_v_id`)
    REFERENCES `isvsk_v2`.`reciver_in_diff_v` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `isvsk_v2`.`reports`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `isvsk_v2`.`reports` (
  `id` INT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `result` TINYINT(1) NOT NULL,
  `path_to_file` VARCHAR(255) NOT NULL,
  `employees_id` INT(5) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `employees_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `path_to_file_UNIQUE` (`path_to_file` ASC),
  UNIQUE INDEX `title_UNIQUE` (`title` ASC),
  INDEX `fk_reports_employees1_idx` (`employees_id` ASC),
  CONSTRAINT `fk_reports_employees1`
    FOREIGN KEY (`employees_id`)
    REFERENCES `isvsk_v2`.`employees` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `isvsk_v2`.`reports_has_device_manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `isvsk_v2`.`reports_has_device_manager` (
  `reports_id` INT(5) UNSIGNED NOT NULL,
  `device_manager_inventnumber` VARCHAR(15) NOT NULL,
  `device_manager_serialnumber` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`reports_id`, `device_manager_inventnumber`, `device_manager_serialnumber`),
  INDEX `fk_reports_has_device_manager_device_manager1_idx` (`device_manager_inventnumber` ASC, `device_manager_serialnumber` ASC),
  INDEX `fk_reports_has_device_manager_reports1_idx` (`reports_id` ASC),
  CONSTRAINT `fk_reports_has_device_manager_reports1`
    FOREIGN KEY (`reports_id`)
    REFERENCES `isvsk_v2`.`reports` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reports_has_device_manager_device_manager1`
    FOREIGN KEY (`device_manager_inventnumber` , `device_manager_serialnumber`)
    REFERENCES `isvsk_v2`.`device_manager` (`inventnumber` , `serialnumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `isvsk_v2`.`statistics_program`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `isvsk_v2`.`statistics_program` (
  `id` INT(3) UNSIGNED NOT NULL AUTO_INCREMENT,
  `runtime` TIME NOT NULL,
  `count_starts` INT(5) NOT NULL,
  `total_number_reports` INT(5) NOT NULL,
  `total_successful_reports` INT(5) NOT NULL,
  `total_failure_reports` INT(5) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `runtime_UNIQUE` (`runtime` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `isvsk_v2`.`hard_soft_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `isvsk_v2`.`hard_soft_data` (
  `id` INT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `pc_name` VARCHAR(150) NOT NULL,
  `username` VARCHAR(150) NOT NULL,
  `os_version` VARCHAR(150) NOT NULL,
  `os_bit_width` TINYINT(1) NOT NULL,
  `ram_width` INT(4) NOT NULL,
  `proc_name` VARCHAR(100) NOT NULL,
  `proc_count_log_proc` INT(2) NULL,
  `proc_count_phys_proc` INT(2) NOT NULL,
  `video_name_card` VARCHAR(150) NOT NULL,
  `dotnet_version` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `pc_name_UNIQUE` (`pc_name` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `dotnet_version_UNIQUE` (`dotnet_version` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
